//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPC_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FullContract
    {
        public int ID { get; set; }
        public string FullContractCode { get; set; }
        public string CustomerName { get; set; }
        public int YearOfBirth { get; set; }
        public string SSN { get; set; }
        public string CustomerAddress { get; set; }
        public string Mobile { get; set; }
        public int PropertyID { get; set; }
        public System.DateTime DateOfContract { get; set; }
        public int Price { get; set; }
        public int Deposit { get; set; }
        public int Remain { get; set; }
        public bool Status { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
